=begin
#LINE Messaging API

#This document describes LINE Messaging API.

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0

=end

require 'date'
require 'time'

module LINE::Client::MessagingApi
  class RichMenuResponse
    # ID of a rich menu
    attr_accessor :rich_menu_id

    attr_accessor :size

    # `true` to display the rich menu by default. Otherwise, `false`.
    attr_accessor :selected

    # Name of the rich menu. This value can be used to help manage your rich menus and is not displayed to users.
    attr_accessor :name

    # Text displayed in the chat bar
    attr_accessor :chat_bar_text

    # Array of area objects which define the coordinates and size of tappable areas
    attr_accessor :areas

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'rich_menu_id' => :'richMenuId',
        :'size' => :'size',
        :'selected' => :'selected',
        :'name' => :'name',
        :'chat_bar_text' => :'chatBarText',
        :'areas' => :'areas'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Returns the key-value map of all the JSON attributes this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'rich_menu_id' => :'String',
        :'size' => :'RichMenuSize',
        :'selected' => :'Boolean',
        :'name' => :'String',
        :'chat_bar_text' => :'String',
        :'areas' => :'Array<RichMenuArea>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `LINE::Client::MessagingApi::RichMenuResponse` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `LINE::Client::MessagingApi::RichMenuResponse`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'rich_menu_id')
        self.rich_menu_id = attributes[:'rich_menu_id']
      else
        self.rich_menu_id = nil
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      else
        self.size = nil
      end

      if attributes.key?(:'selected')
        self.selected = attributes[:'selected']
      else
        self.selected = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'chat_bar_text')
        self.chat_bar_text = attributes[:'chat_bar_text']
      else
        self.chat_bar_text = nil
      end

      if attributes.key?(:'areas')
        if (value = attributes[:'areas']).is_a?(Array)
          self.areas = value
        end
      else
        self.areas = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @rich_menu_id.nil?
        invalid_properties.push('invalid value for "rich_menu_id", rich_menu_id cannot be nil.')
      end

      if @size.nil?
        invalid_properties.push('invalid value for "size", size cannot be nil.')
      end

      if @selected.nil?
        invalid_properties.push('invalid value for "selected", selected cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @name.to_s.length > 300
        invalid_properties.push('invalid value for "name", the character length must be smaller than or equal to 300.')
      end

      if @chat_bar_text.nil?
        invalid_properties.push('invalid value for "chat_bar_text", chat_bar_text cannot be nil.')
      end

      if @chat_bar_text.to_s.length > 14
        invalid_properties.push('invalid value for "chat_bar_text", the character length must be smaller than or equal to 14.')
      end

      if @areas.nil?
        invalid_properties.push('invalid value for "areas", areas cannot be nil.')
      end

      if @areas.length > 20
        invalid_properties.push('invalid value for "areas", number of items must be less than or equal to 20.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @rich_menu_id.nil?
      return false if @size.nil?
      return false if @selected.nil?
      return false if @name.nil?
      return false if @name.to_s.length > 300
      return false if @chat_bar_text.nil?
      return false if @chat_bar_text.to_s.length > 14
      return false if @areas.nil?
      return false if @areas.length > 20
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      if name.to_s.length > 300
        fail ArgumentError, 'invalid value for "name", the character length must be smaller than or equal to 300.'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] chat_bar_text Value to be assigned
    def chat_bar_text=(chat_bar_text)
      if chat_bar_text.nil?
        fail ArgumentError, 'chat_bar_text cannot be nil'
      end

      if chat_bar_text.to_s.length > 14
        fail ArgumentError, 'invalid value for "chat_bar_text", the character length must be smaller than or equal to 14.'
      end

      @chat_bar_text = chat_bar_text
    end

    # Custom attribute writer method with validation
    # @param [Object] areas Value to be assigned
    def areas=(areas)
      if areas.nil?
        fail ArgumentError, 'areas cannot be nil'
      end

      if areas.length > 20
        fail ArgumentError, 'invalid value for "areas", number of items must be less than or equal to 20.'
      end

      @areas = areas
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          rich_menu_id == o.rich_menu_id &&
          size == o.size &&
          selected == o.selected &&
          name == o.name &&
          chat_bar_text == o.chat_bar_text &&
          areas == o.areas
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [rich_menu_id, size, selected, name, chat_bar_text, areas].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = LINE::Client::MessagingApi.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
