=begin
#Channel Access Token API

#This document describes Channel Access Token API.

The version of the OpenAPI document: 0.0.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0

=end

# Common files
require 'line_client_channel_access_token/api_client'
require 'line_client_channel_access_token/api_error'
require 'line_client_channel_access_token/version'
require 'line_client_channel_access_token/configuration'

# Models
require 'line_client_channel_access_token/models/channel_access_token_key_ids_response'
require 'line_client_channel_access_token/models/error_response'
require 'line_client_channel_access_token/models/issue_channel_access_token_response'
require 'line_client_channel_access_token/models/issue_short_lived_channel_access_token_response'
require 'line_client_channel_access_token/models/issue_stateless_channel_access_token_response'
require 'line_client_channel_access_token/models/verify_channel_access_token_response'

# APIs
require 'line_client_channel_access_token/api/channel_access_token_api'

module LINE::Client::ChannelAccessToken
  class << self
    # Customize default settings for the SDK using block.
    #   LINE::Client::ChannelAccessToken.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
