AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'examples/**/*'
    - 'lib/line/bot/v1/**/*'
    - 'lib/line/bot/v2/channel_access_token/**/*'
    - 'lib/line/bot/v2/insight/**/*'
    - 'lib/line/bot/v2/liff/**/*'
    - 'lib/line/bot/v2/manage_audience/**/*'
    - 'lib/line/bot/v2/messaging_api/**/*'
    - 'lib/line/bot/v2/module/**/*'
    - 'lib/line/bot/v2/module_attach/**/*'
    - 'lib/line/bot/v2/shop/**/*'
    - 'lib/line/bot/v2/webhook/**/*'
  NewCops: disable

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/SafeNavigation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/ConstantName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Max: 200
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/DotPosition:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false
Lint/DuplicateMethods:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
