AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - 'examples/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/EachWithObject:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Naming/ConstantName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MethodName:
  Enabled: false

Metrics/LineLength:
  Max: 200
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/AbcSize:
  Max: 20

Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/IndentHeredoc:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false
Lint/DuplicateMethods:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
