AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'examples/**/*'
  NewCops: disable

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Naming/ConstantName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/FileName:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 200
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false
Lint/DuplicateMethods:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
