# LIFF server API
# LIFF Server API.
#
# The version of the OpenAPI document: 1.0.0
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module Liff
        class LiffFeatures
          attr_accessor :ble # `true` if the LIFF app supports Bluetooth® Low Energy for LINE Things. `false` otherwise. 
          attr_accessor :qr_code # `true` to use the 2D code reader in the LIFF app. false otherwise. The default value is `false`. 

          def initialize(
            ble: nil,
            qr_code: false,
            **dynamic_attributes
          )
            
            @ble = ble
            @qr_code = qr_code

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key
              instance_variable_set("@#{key}", value)
            end
          end
        end
      end
    end
  end
end
