module Line
  module Bot
    module V2
      class WebhookParser
        class InvalidSignatureError < ::StandardError
        end

        def initialize: (channel_secret: String) -> void

        def parse: (
            body: String,
            signature: String
          ) -> Array[Webhook::Event]

        private

        def variable_secure_compare: (a: String, b: String) -> bool

        def secure_compare: (a: String, b: String) -> bool

        def verify_signature: (body: String, signature: String) -> bool
      end
    end
  end
end
