service: aws-ruby-line-bot

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: ruby2.5

functions:
  current_time:
    handler: handler.webhook
    events:
      - http:
          path: webhook
          method: post

plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      - bundle install --deployment
