# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

# @see https://developers.line.biz/en/reference/partner-docs/#phone-audience-match
module Line
  module Bot
    module V2
      module MessagingApi
        class AudienceMatchMessagesRequest
          attr_accessor :messages # Destination of the message (A value obtained by hashing the telephone number, which is another value normalized to E.164 format, with SHA256).
          attr_accessor :to # Message to send.
          attr_accessor :notification_disabled # `true`: The user doesn’t receive a push notification when a message is sent. `false`: The user receives a push notification when the message is sent (unless they have disabled push notifications in LINE and/or their device). The default value is false. 

          def initialize(
            messages:,
            to:,
            notification_disabled: false
          )
            
            @messages = messages
            @to = to
            @notification_disabled = notification_disabled
          end
        end
      end
    end
  end
end
