# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './action'

# @see https://developers.line.biz/en/reference/messaging-api/#clipboard-action
module Line
  module Bot
    module V2
      module MessagingApi
        class ClipboardAction < Action
          attr_accessor :type # Type of action
          attr_accessor :label # Label for the action.
          attr_accessor :clipboard_text # Text that is copied to the clipboard. Max character limit: 1000 

          def initialize(
            type: nil,
            label: nil,
            clipboard_text:
          )
            @type = type
            @label = label
            @clipboard_text = clipboard_text
          end
        end
      end
    end
  end
end
