# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './action'

module Line
  module Bot
    module V2
      module MessagingApi
        # @see https://developers.line.biz/en/reference/messaging-api/#datetime-picker-action
        class DatetimePickerAction < Action
          # @!attribute [r] type
          #   @return [String,nil] Type of action
          attr_reader :type
          # @!attribute [rw] label
          #   @return [String,nil] Label for the action.
          attr_accessor :label
          # @!attribute [rw] data
          #   @return [String,nil] 
          attr_accessor :data
          # @!attribute [rw] mode
          #   @return [String,nil] ('date'|'time'|'datetime') 
          attr_accessor :mode
          # @!attribute [rw] initial
          #   @return [String,nil] 
          attr_accessor :initial
          # @!attribute [rw] max
          #   @return [String,nil] 
          attr_accessor :max
          # @!attribute [rw] min
          #   @return [String,nil] 
          attr_accessor :min

          # @param label [String,nil] Label for the action.
          # @param data [String,nil] 
          # @param mode [String,nil] ('date'|'time'|'datetime') 
          # @param initial [String,nil] 
          # @param max [String,nil] 
          # @param min [String,nil] 
          def initialize(
            label: nil,
            data: nil,
            mode: nil,
            initial: nil,
            max: nil,
            min: nil,
            **dynamic_attributes
          )
            @type = "datetimepicker"
            
            @label = label
            @data = data
            @mode = mode
            @initial = initial
            @max = max
            @min = min

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args)
            return new(**args)
          end
        end
      end
    end
  end
end
