# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module MessagingApi
        class Emoji
          attr_accessor :index
          attr_accessor :product_id
          attr_accessor :emoji_id

          def initialize(
            index: nil,
            product_id: nil,
            emoji_id: nil
          )
            @index = index
            @product_id = product_id
            @emoji_id = emoji_id
          end
        end
      end
    end
  end
end
