# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './flex_component'

module Line
  module Bot
    module V2
      module MessagingApi
        class FlexFiller < FlexComponent
          attr_reader :type
          attr_accessor :flex

          def initialize(
            flex: nil
          )
            @type = "filler"
            
            @flex = flex
          end
        end
      end
    end
  end
end
