# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './flex_component'

module Line
  module Bot
    module V2
      module MessagingApi
        class FlexVideo < FlexComponent
          attr_accessor :type
          attr_accessor :url
          attr_accessor :preview_url
          attr_accessor :alt_content
          attr_accessor :aspect_ratio
          attr_accessor :action

          def initialize(
            type:,
            url:,
            preview_url:,
            alt_content:,
            aspect_ratio: nil,
            action: nil
          )
            @type = type
            @url = url
            @preview_url = preview_url
            @alt_content = alt_content
            @aspect_ratio = aspect_ratio
            @action = action
          end
        end
      end
    end
  end
end
