# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './flex_component'

module Line
  module Bot
    module V2
      module MessagingApi
        class FlexVideo < FlexComponent
          # @!attribute [r] type
          #   @return [String] 
          attr_reader :type
          # @!attribute [rw] url
          #   @return [String] 
          attr_accessor :url
          # @!attribute [rw] preview_url
          #   @return [String] 
          attr_accessor :preview_url
          # @!attribute [rw] alt_content
          #   @return [FlexComponent] 
          attr_accessor :alt_content
          # @!attribute [rw] aspect_ratio
          #   @return [String,nil] 
          attr_accessor :aspect_ratio
          # @!attribute [rw] action
          #   @return [Action,nil] 
          attr_accessor :action

          # @param url [String] 
          # @param preview_url [String] 
          # @param alt_content [FlexComponent, Hash[Symbol, untyped]] 
          # @param aspect_ratio [String,nil] 
          # @param action [Action, Hash[Symbol, untyped], nil] 
          def initialize(
            url:,
            preview_url:,
            alt_content:,
            aspect_ratio: nil,
            action: nil,
            **dynamic_attributes
          )
            @type = "video"
            
            @url = url
            @preview_url = preview_url
            @alt_content = alt_content.is_a?(Line::Bot::V2::MessagingApi::FlexComponent) ? alt_content : Line::Bot::V2::MessagingApi::FlexComponent.create(**alt_content) # steep:ignore
            @aspect_ratio = aspect_ratio
            @action = action.is_a?(Line::Bot::V2::MessagingApi::Action) || action.nil? ? action : Line::Bot::V2::MessagingApi::Action.create(**action) # steep:ignore

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          # Create an instance of the class from a hash
          # @param args [Hash] Hash containing all the required attributes
          # @return [Line::Bot::V2::MessagingApi::FlexVideo] Instance of the class
          def self.create(args) # steep:ignore
            symbolized_args = Line::Bot::V2::Utils.deep_symbolize(args)
            return new(**symbolized_args) # steep:ignore
          end

          # @param other [Object] Object to compare
          # @return [Boolean] true if the objects are equal, false otherwise
          def ==(other)
            return false unless self.class == other.class

            instance_variables.all? do |var|
                instance_variable_get(var) == other.instance_variable_get(var)
            end
          end

          # @return [Integer] Hash code of the object
          def hash
            [self.class, *instance_variables.map { |var| instance_variable_get(var) }].hash
          end
        end
      end
    end
  end
end
