# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './flex_container'

module Line
  module Bot
    module V2
      module MessagingApi
        class FlexBubble < FlexContainer
          # @!attribute [r] type
          #   @return [String] 
          attr_reader :type
          # @!attribute [rw] direction
          #   @return [String,nil] ('ltr'|'rtl') 
          attr_accessor :direction
          # @!attribute [rw] styles
          #   @return [FlexBubbleStyles,nil] 
          attr_accessor :styles
          # @!attribute [rw] header
          #   @return [FlexBox,nil] 
          attr_accessor :header
          # @!attribute [rw] hero
          #   @return [FlexComponent,nil] 
          attr_accessor :hero
          # @!attribute [rw] body
          #   @return [FlexBox,nil] 
          attr_accessor :body
          # @!attribute [rw] footer
          #   @return [FlexBox,nil] 
          attr_accessor :footer
          # @!attribute [rw] size
          #   @return [String,nil] ('nano'|'micro'|'deca'|'hecto'|'kilo'|'mega'|'giga') 
          attr_accessor :size
          # @!attribute [rw] action
          #   @return [Action,nil] 
          attr_accessor :action

          # @param direction [String,nil] ('ltr'|'rtl') 
          # @param styles [FlexBubbleStyles,nil] 
          # @param header [FlexBox,nil] 
          # @param hero [FlexComponent,nil] 
          # @param body [FlexBox,nil] 
          # @param footer [FlexBox,nil] 
          # @param size [String,nil] ('nano'|'micro'|'deca'|'hecto'|'kilo'|'mega'|'giga') 
          # @param action [Action,nil] 
          def initialize(
            direction: nil,
            styles: nil,
            header: nil,
            hero: nil,
            body: nil,
            footer: nil,
            size: nil,
            action: nil,
            **dynamic_attributes
          )
            @type = "bubble"
            
            @direction = direction
            @styles = styles.is_a?(Line::Bot::V2::MessagingApi::FlexBubbleStyles) || styles.nil? ? styles : Line::Bot::V2::MessagingApi::FlexBubbleStyles.create(**styles)
            @header = header.is_a?(Line::Bot::V2::MessagingApi::FlexBox) || header.nil? ? header : Line::Bot::V2::MessagingApi::FlexBox.create(**header)
            @hero = hero.is_a?(Line::Bot::V2::MessagingApi::FlexComponent) || hero.nil? ? hero : Line::Bot::V2::MessagingApi::FlexComponent.create(**hero)
            @body = body.is_a?(Line::Bot::V2::MessagingApi::FlexBox) || body.nil? ? body : Line::Bot::V2::MessagingApi::FlexBox.create(**body)
            @footer = footer.is_a?(Line::Bot::V2::MessagingApi::FlexBox) || footer.nil? ? footer : Line::Bot::V2::MessagingApi::FlexBox.create(**footer)
            @size = size
            @action = action.is_a?(Line::Bot::V2::MessagingApi::Action) || action.nil? ? action : Line::Bot::V2::MessagingApi::Action.create(**action)

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args)
            return new(**args)
          end
        end
      end
    end
  end
end
