# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module MessagingApi
        # A user's membership subscription status
        # @see https://developers.line.biz/en/reference/messaging-api/#get-a-users-membership-subscription-status
        class GetMembershipSubscriptionResponse
          # @!attribute [rw] subscriptions
          #   @return [Array[Subscription]] List of subscription information
          attr_accessor :subscriptions

          # @param subscriptions [Array[Subscription]] List of subscription information
          def initialize(
            subscriptions:,
            **dynamic_attributes
          )
            
            @subscriptions = subscriptions.map do |item|
              if item.is_a?(Hash)
                Line::Bot::V2::MessagingApi::Subscription.create(**item)
              else
                item
              end
            end

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args) # steep:ignore
            return new(**args) # steep:ignore
          end
        end
      end
    end
  end
end
