# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module MessagingApi
        class ImagemapVideo
          # @!attribute [rw] original_content_url
          #   @return [String] 
          attr_accessor :original_content_url
          # @!attribute [rw] preview_image_url
          #   @return [String] 
          attr_accessor :preview_image_url
          # @!attribute [rw] area
          #   @return [ImagemapArea] 
          attr_accessor :area
          # @!attribute [rw] external_link
          #   @return [ImagemapExternalLink] 
          attr_accessor :external_link

          # @param original_content_url [String] 
          # @param preview_image_url [String] 
          # @param area [ImagemapArea] 
          # @param external_link [ImagemapExternalLink] 
          def initialize(
            original_content_url: nil,
            preview_image_url: nil,
            area: nil,
            external_link: nil,
            **dynamic_attributes
          )
            
            @original_content_url = original_content_url
            @preview_image_url = preview_image_url
            @area = area.is_a?(Line::Bot::V2::MessagingApi::ImagemapArea) || area.nil? ? area : Line::Bot::V2::MessagingApi::ImagemapArea.create(**area)
            @external_link = external_link.is_a?(Line::Bot::V2::MessagingApi::ImagemapExternalLink) || external_link.nil? ? external_link : Line::Bot::V2::MessagingApi::ImagemapExternalLink.create(**external_link)

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args)
            return new(**args)
          end
        end
      end
    end
  end
end
