# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module MessagingApi
        # @see https://developers.line.biz/en/reference/messaging-api/#message-common-properties
        class Message
          attr_accessor :type # Type of message
          attr_accessor :quick_reply
          attr_accessor :sender

          def initialize(
            type:,
            quick_reply: nil,
            sender: nil,
            **dynamic_attributes
          )
            
            @type = type
            @quick_reply = quick_reply
            @sender = sender

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key
              instance_variable_set("@#{key}", value)
            end
          end
        end
      end
    end
  end
end
