# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './action'

module Line
  module Bot
    module V2
      module MessagingApi
        class PostbackAction < Action
          attr_reader :type # Type of action
          attr_accessor :label # Label for the action.
          attr_accessor :data
          attr_accessor :display_text
          attr_accessor :text
          attr_accessor :input_option
          attr_accessor :fill_in_text

          def initialize(
            label: nil,
            data: nil,
            display_text: nil,
            text: nil,
            input_option: nil,
            fill_in_text: nil,
            **dynamic_attributes
          )
            @type = "postback"
            
            @label = label
            @data = data
            @display_text = display_text
            @text = text
            @input_option = input_option
            @fill_in_text = fill_in_text

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args)
            return new(**args)
          end
        end
      end
    end
  end
end
