# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './recipient'

module Line
  module Bot
    module V2
      module MessagingApi
        class RedeliveryRecipient < Recipient
          attr_reader :type # Type of recipient
          attr_accessor :request_id

          def initialize(
            request_id: nil
          )
            @type = "redelivery"
            
            @request_id = request_id
          end
        end
      end
    end
  end
end
