# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module MessagingApi
        # Rich menu area
        class RichMenuArea
          # @!attribute [rw] bounds
          #   @return [RichMenuBounds,nil] 
          attr_accessor :bounds
          # @!attribute [rw] action
          #   @return [Action,nil] 
          attr_accessor :action

          # @param bounds [RichMenuBounds,nil] 
          # @param action [Action,nil] 
          def initialize(
            bounds: nil,
            action: nil,
            **dynamic_attributes
          )
            
            @bounds = bounds.is_a?(Line::Bot::V2::MessagingApi::RichMenuBounds) || bounds.nil? ? bounds : Line::Bot::V2::MessagingApi::RichMenuBounds.create(**bounds) # steep:ignore
            @action = action.is_a?(Line::Bot::V2::MessagingApi::Action) || action.nil? ? action : Line::Bot::V2::MessagingApi::Action.create(**action) # steep:ignore

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args) # steep:ignore
            return new(**args) # steep:ignore
          end

          # @param other [Object] Object to compare
          # @return [Boolean] true if the objects are equal, false otherwise
          def ==(other)
            return false unless self.class == other.class

            instance_variables.all? do |var|
                instance_variable_get(var) == other.instance_variable_get(var)
            end
          end

          # @return [Integer] Hash code of the object
          def hash
            [self.class, *instance_variables.map { |var| instance_variable_get(var) }].hash
          end
        end
      end
    end
  end
end
