# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module MessagingApi
        class RichMenuBatchRequest
          attr_accessor :operations # Array of Rich menu operation object...
          attr_accessor :resume_request_key # Key for retry. Key value is a string matching the regular expression pattern

          def initialize(
            operations:,
            resume_request_key: nil
          )
            @operations = operations
            @resume_request_key = resume_request_key
          end
        end
      end
    end
  end
end
