# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './rich_menu_batch_operation'

module Line
  module Bot
    module V2
      module MessagingApi
        # Replace the rich menu with the rich menu specified in the `to` property for all users linked to the rich menu specified in the `from` property.
        class RichMenuBatchLinkOperation < RichMenuBatchOperation
          # @!attribute [r] type
          #   @return [String] The type of operation to the rich menu linked to the user. One of link, unlink, or unlinkAll.
          attr_reader :type
          # @!attribute [rw] from
          #   @return [String] 
          attr_accessor :from
          # @!attribute [rw] to
          #   @return [String] 
          attr_accessor :to

          # @param from [String] 
          # @param to [String] 
          def initialize(
            from:,
            to:,
            **dynamic_attributes
          )
            @type = "link"
            
            @from = from
            @to = to

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          # Create an instance of the class from a hash
          # @param args [Hash] Hash containing all the required attributes
          # @return [Line::Bot::V2::MessagingApi::RichMenuBatchLinkOperation] Instance of the class
          def self.create(args) # steep:ignore
            symbolized_args = Line::Bot::V2::Utils.deep_symbolize(args)
            return new(**symbolized_args) # steep:ignore
          end

          # @param other [Object] Object to compare
          # @return [Boolean] true if the objects are equal, false otherwise
          def ==(other)
            return false unless self.class == other.class

            instance_variables.all? do |var|
                instance_variable_get(var) == other.instance_variable_get(var)
            end
          end

          # @return [Integer] Hash code of the object
          def hash
            [self.class, *instance_variables.map { |var| instance_variable_get(var) }].hash
          end
        end
      end
    end
  end
end
