# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module MessagingApi
        # Object containing user membership subscription information.
        class SubscribedMembershipUser
          attr_accessor :membership_no # The user's member number in the membership plan.
          attr_accessor :joined_time # UNIX timestamp at which the user subscribed to the membership.
          attr_accessor :next_billing_date # Next payment date for membership plan. - Format: yyyy-MM-dd (e.g. 2024-02-08) - Timezone: UTC+9 
          attr_accessor :total_subscription_months # The period of time in months that the user has been subscribed to a membership plan. If a user previously canceled and then re-subscribed to the same membership plan, only the period after the re-subscription will be counted.

          def initialize(
            membership_no:,
            joined_time:,
            next_billing_date:,
            total_subscription_months:,
            **dynamic_attributes
          )
            
            @membership_no = membership_no
            @joined_time = joined_time
            @next_billing_date = next_billing_date
            @total_subscription_months = total_subscription_months

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args)
            return new(**args)
          end
        end
      end
    end
  end
end
