# frozen_string_literal: true

source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'line-bot-api'
gem "puma"
gem "rackup"
gem "sinatra"
gem "webrick"
