# frozen_string_literal: true

module UnifiedClientGenerator
  module_function

  # --- Comment qualification ---

  def qualify_comment(comment, ns, models)
    return '' if comment.nil? || comment.empty?

    comment.each_line.map do |line|
      if line.include?('[') && (line.include?('@param') || line.include?('@return'))
        line.gsub(/\[([^\]]+)\]/) { "[#{qualify_types(::Regexp.last_match(1), ns, models)}]" }
      else
        line
      end
    end.join
  end

  def qualify_types(expr, ns, models)
    expr.gsub(/(?<!::)(?<![A-Za-z0-9_])([A-Z][A-Za-z0-9_]*)\b/) do
      t = Regexp.last_match(1)
      BUILTINS.include?(t) || !models.include?(t) ? t : "Line::Bot::V2::#{ns}::#{t}"
    end
  end

  # --- Shared ---

  def render_comment(comment)
    comment.each_line.map { |l| (s = l.rstrip).empty? ? '#' : "# #{s}" }.join("\n")
  end

  # --- Ruby rendering ---

  def render_ruby_method(client, method)
    parts = []
    parts << render_comment(method.comment) unless method.comment.empty?

    all_kw = method.required_keywords.keys.map { |k| "  #{k}:" } +
             method.optional_keywords.keys.map { |k| "  #{k}: nil" }
    parts << if all_kw.empty?
               "def #{method.name}"
             else
               "def #{method.name}(\n#{all_kw.join(",\n")}\n)"
             end

    fwd = (method.required_keywords.keys + method.optional_keywords.keys).map { |k| "#{k}: #{k}" }
    parts << if fwd.empty?
               "  #{client.ivar_name}.#{method.name}"
             else
               "  #{client.ivar_name}.#{method.name}(\n#{indent(fwd.join(",\n"), 4)}\n  )"
             end
    parts << 'end'
    parts.join("\n")
  end

  def render_generated_ruby(clients)
    methods = clients.flat_map { |c| c.delegated_methods.map { |m| render_ruby_method(c, m) } }.join("\n\n")

    <<~RUBY
      # This file is autogenerated.
      #
      # Generated by scripts/unified-client-generator/main.rb
      # Do not edit this file directly.

      module Line
        module Bot
          module V2
            class LineBotClient
      #{indent(methods, 8)}
            end
          end
        end
      end
    RUBY
  end

  def render_factory_ruby(clients)
    assignments = clients.map { |c| render_factory_assignment(c) }.join("\n\n")

    <<~RUBY
      # This file is autogenerated.
      #
      # Generated by scripts/unified-client-generator/main.rb
      # Do not edit this file directly.

      module Line
        module Bot
          module V2
            class LineBotClient
              private

              def build_generated_delegates(
                channel_access_token:,
                api_base_url: nil,
                data_api_base_url: nil,
                http_options: {}
              )
      #{indent(assignments, 10)}
                nil
              end
            end
          end
        end
      end
    RUBY
  end

  BASE_URL_MAP = {
    'https://api.line.me' => 'api_base_url',
    'https://api-data.line.me' => 'data_api_base_url'
  }.freeze

  def render_factory_assignment(client)
    base_url_kw = BASE_URL_MAP[client.default_base_url]

    supports = lambda do |key|
      client.constructor_required_keywords.include?(key) ||
        client.constructor_optional_keywords.include?(key)
    end

    args = []
    args << "base_url: #{base_url_kw}" if supports.call('base_url') && base_url_kw
    args << 'channel_access_token: channel_access_token' if supports.call('channel_access_token')
    args << 'http_options: http_options' if supports.call('http_options')

    "#{client.ivar_name} = #{client.qualified_class_name}.\n  new(#{args.join(', ')})"
  end

  # --- RBS rendering ---

  def render_rbs(clients)
    ivars = clients.map { |c| "@#{c.delegate_name}: #{c.namespace_reference}::#{c.class_name}" }.join("\n")
    pub = clients.flat_map { |c| c.delegated_methods.map { |m| render_rbs_method(m) } }.join("\n\n")

    <<~RBS
      # This file is autogenerated.
      #
      # Generated by scripts/unified-client-generator/main.rb
      # Do not edit this file directly.

      module Line
        module Bot
          module V2
            class LineBotClient
      #{indent(render_comment(CLIENT_CLASS_COMMENT), 8)}
      #{indent(ivars, 8)}

      #{indent(render_comment(CLIENT_INITIALIZE_COMMENT), 8)}
              def initialize: (
                channel_access_token: String,
                ?api_base_url: String?,
                ?data_api_base_url: String?,
                ?http_options: Hash[String | Symbol, untyped]
              ) -> void

      #{indent(pub, 8)}

              private

              def build_generated_delegates: (
                channel_access_token: String,
                ?api_base_url: String?,
                ?data_api_base_url: String?,
                ?http_options: Hash[String | Symbol, untyped]
              ) -> void
            end
          end
        end
      end
    RBS
  end

  def render_rbs_method(method)
    parts = []
    parts << render_comment(method.comment) unless method.comment.empty?

    kw = method.required_keywords.map { |k, t| "#{k}: #{t}" } +
         method.optional_keywords.map { |k, t| "?#{k}: #{t}" }

    ret = render_rbs_return_type(method.return_type)
    if kw.empty?
      parts << "def #{method.name}: () -> #{ret}"
    else
      parts << "def #{method.name}: ("
      parts << indent(kw.join(",\n"), 2)
      parts << ") -> #{ret}"
    end
    parts.join("\n")
  end

  def render_rbs_return_type(return_type)
    if return_type.include?(' | ') && return_type.length > 100
      parts = return_type.split(' | ')
      "(\n#{indent(parts.join("\n| "), 2)}\n)"
    else
      "(#{return_type})"
    end
  end
end
