# Webhook Type Definition
# Webhook event definition of the LINE Messaging API
#
# The version of the OpenAPI document: 1.0.0
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './mentionee'

module Line
  module Bot
    module V2
      module Webhook
        # Mentioned target is entire group
        class AllMentionee < Mentionee
          # @!attribute [r] type
          #   @return [String] Mentioned target.
          attr_reader :type
          # @!attribute [rw] index
          #   @return [Integer] Index position of the user mention for a character in text, with the first character being at position 0.
          attr_accessor :index
          # @!attribute [rw] length
          #   @return [Integer] The length of the text of the mentioned user. For a mention @example, 8 is the length.
          attr_accessor :length

          # @param index [Integer] Index position of the user mention for a character in text, with the first character being at position 0.
          # @param length [Integer] The length of the text of the mentioned user. For a mention @example, 8 is the length.
          def initialize(
            index:,
            length:,
            **dynamic_attributes
          )
            @type = "all"
            
            @index = index
            @length = length

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args)
            return new(**args)
          end
        end
      end
    end
  end
end
