# Webhook Type Definition
# Webhook event definition of the LINE Messaging API
#
# The version of the OpenAPI document: 1.0.0
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

require_relative './membership_content'

module Line
  module Bot
    module V2
      module Webhook
        class LeftMembershipContent < MembershipContent
          attr_reader :type # Type of membership event.
          attr_accessor :membership_id # The ID of the membership that the user left. This is defined for each membership.

          def initialize(
            type:,
            membership_id:
          )
            @type = "left"
            
            @membership_id = membership_id
          end
        end
      end
    end
  end
end
