# Webhook Type Definition
# Webhook event definition of the LINE Messaging API
#
# The version of the OpenAPI document: 1.0.0
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module Webhook
        # @see https://developers.line.biz/en/reference/messaging-api/#message-event
        class MessageContent
          # @!attribute [rw] type
          #   @return [String] Type
          attr_accessor :type
          # @!attribute [rw] id
          #   @return [String] Message ID
          attr_accessor :id

          # @param type [String] Type
          # @param id [String] Message ID
          def initialize(
            type:,
            id:,
            **dynamic_attributes
          )
            
            @type = type
            @id = id

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args)
            klass = detect_class(args[:type])
            return klass.new(**args) if klass
            
            return new(**args)
          end

          private

          def self.detect_class(type)
            {
              audio: Line::Bot::V2::Webhook::AudioMessageContent,
              file: Line::Bot::V2::Webhook::FileMessageContent,
              image: Line::Bot::V2::Webhook::ImageMessageContent,
              location: Line::Bot::V2::Webhook::LocationMessageContent,
              sticker: Line::Bot::V2::Webhook::StickerMessageContent,
              text: Line::Bot::V2::Webhook::TextMessageContent,
              video: Line::Bot::V2::Webhook::VideoMessageContent,
            }[type.to_sym]
          end
        end
      end
    end
  end
end
