# Webhook Type Definition
# Webhook event definition of the LINE Messaging API
#
# The version of the OpenAPI document: 1.0.0
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module Webhook
        class UnsendDetail
          attr_accessor :message_id # The message ID of the unsent message

          def initialize(
            message_id:
          )
            
            @message_id = message_id
          end
        end
      end
    end
  end
end
