=begin
#Webhook Type Definition

#Webhook event definition of the LINE Messaging API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.6.0

=end

require 'date'
require 'time'

module LINE::Client::Webhook
  class EventMode
    ACTIVE = "active".freeze
    STANDBY = "standby".freeze

    def self.all_vars
      @all_vars ||= [ACTIVE, STANDBY].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if EventMode.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #EventMode"
    end
  end
end
