# LINE Messaging API(Insight)
# This document describes LINE Messaging API(Insight).
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

# Statistics about how users interact with narrowcast messages or broadcast messages sent from your LINE Official Account.
# @see https://developers.line.biz/en/reference/messaging-api/#get-insight-message-event-response
module Line
  module Bot
    module V2
      module Insight
        class GetMessageEventResponse
          attr_accessor :overview
          attr_accessor :messages # Array of information about individual message bubbles.
          attr_accessor :clicks # Array of information about opened URLs in the message.

          def initialize(
            overview: nil,
            messages: nil,
            clicks: nil
          )
            
            @overview = overview
            @messages = messages
            @clicks = clicks
          end
        end
      end
    end
  end
end
