# LINE Messaging API(Insight)
# This document describes LINE Messaging API(Insight).
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module Insight
        # Statistics related to messages.
        # @see https://developers.line.biz/en/reference/messaging-api/#get-statistics-per-unit-response
        class GetStatisticsPerUnitResponseOverview
          # @!attribute [rw] unique_impression
          #   @return [Integer] Number of users who opened the message, meaning they displayed at least 1 bubble.
          attr_accessor :unique_impression
          # @!attribute [rw] unique_click
          #   @return [Integer] Number of users who opened any URL in the message.
          attr_accessor :unique_click
          # @!attribute [rw] unique_media_played
          #   @return [Integer] Number of users who started playing any video or audio in the message.
          attr_accessor :unique_media_played
          # @!attribute [rw] unique_media_played100_percent
          #   @return [Integer] Number of users who played the entirety of any video or audio in the message.
          attr_accessor :unique_media_played100_percent

          # @param unique_impression [Integer] Number of users who opened the message, meaning they displayed at least 1 bubble.
          # @param unique_click [Integer] Number of users who opened any URL in the message.
          # @param unique_media_played [Integer] Number of users who started playing any video or audio in the message.
          # @param unique_media_played100_percent [Integer] Number of users who played the entirety of any video or audio in the message.
          def initialize(
            unique_impression: nil,
            unique_click: nil,
            unique_media_played: nil,
            unique_media_played100_percent: nil,
            **dynamic_attributes
          )
            
            @unique_impression = unique_impression
            @unique_click = unique_click
            @unique_media_played = unique_media_played
            @unique_media_played100_percent = unique_media_played100_percent

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          def self.create(args)
            return new(**args)
          end
        end
      end
    end
  end
end
