# LINE Messaging API(Insight)
# This document describes LINE Messaging API(Insight).
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

module Line
  module Bot
    module V2
      module Insight
        # Aggregated number of events and unique users over the whole period.
        class GetRichMenuInsightSummaryResponseMetrics
          # @!attribute [rw] count
          #   @return [Integer] Number of impressions or clicks.
          attr_accessor :count
          # @!attribute [rw] unique_users
          #   @return [Integer] Approximate number of unique users who triggered an impression or click.
          attr_accessor :unique_users

          # @param count [Integer] Number of impressions or clicks.
          # @param unique_users [Integer] Approximate number of unique users who triggered an impression or click.
          def initialize(
            count:,
            unique_users:,
            **dynamic_attributes
          )
            
            @count = count
            @unique_users = unique_users

            dynamic_attributes.each do |key, value|
              self.class.attr_accessor key

              if value.is_a?(Hash)
                struct_klass = Struct.new(*value.keys.map(&:to_sym))
                struct_values = value.map { |_k, v| v.is_a?(Hash) ? Line::Bot::V2::Utils.hash_to_struct(v) : v }
                instance_variable_set("@#{key}", struct_klass.new(*struct_values))
              else
                instance_variable_set("@#{key}", value)
              end
            end
          end

          # Create an instance of the class from a hash
          # @param args [Hash] Hash containing all the required attributes
          # @return [Line::Bot::V2::Insight::GetRichMenuInsightSummaryResponseMetrics] Instance of the class
          def self.create(args)
            symbolized_args = Line::Bot::V2::Utils.deep_symbolize(args)
            return new(**symbolized_args) # steep:ignore InsufficientKeywordArguments
          end

          # @param other [Object] Object to compare
          # @return [Boolean] true if the objects are equal, false otherwise
          def ==(other)
            return false unless self.class == other.class

            instance_variables.all? do |var|
                instance_variable_get(var) == other.instance_variable_get(var)
            end
          end

          # @return [Integer] Hash code of the object
          def hash
            [self.class, *instance_variables.map { |var| instance_variable_get(var) }].hash
          end
        end
      end
    end
  end
end
