# LINE Messaging API(Insight)
# This document describes LINE Messaging API(Insight).
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

# Get friend demographics
# @see https://developers.line.biz/en/reference/messaging-api/#get-demographic
module Line
  module Bot
    module V2
      module Insight
        class GetFriendsDemographicsResponse
          attr_accessor :available # true if friend demographic information is available.
          attr_accessor :genders # Percentage per gender.
          attr_accessor :ages # Percentage per age group.
          attr_accessor :areas # Percentage per area.
          attr_accessor :app_types # Percentage by OS.
          attr_accessor :subscription_periods # Percentage per friendship duration.

          def initialize(
            available: nil,
            genders: nil,
            ages: nil,
            areas: nil,
            app_types: nil,
            subscription_periods: nil
          )
            
            @available = available
            @genders = genders
            @ages = ages
            @areas = areas
            @app_types = app_types
            @subscription_periods = subscription_periods
          end
        end
      end
    end
  end
end
