
# LIFF server API
# LIFF Server API.
#
# The version of the OpenAPI document: 1.0.0
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

# Models
require_relative './model/add_liff_app_request'
require_relative './model/add_liff_app_response'
require_relative './model/get_all_liff_apps_response'
require_relative './model/liff_app'
require_relative './model/liff_bot_prompt'
require_relative './model/liff_features'
require_relative './model/liff_scope'
require_relative './model/liff_view'
require_relative './model/update_liff_app_request'
require_relative './model/update_liff_view'

# APIs
require_relative './api/liff_client'
