# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

# Create audience for impression-based retargeting
# @see https://developers.line.biz/en/reference/messaging-api/#create-imp-audience-group
module Line
  module Bot
    module V2
      module ManageAudience
        class CreateImpBasedAudienceGroupResponse
          attr_accessor :audience_group_id # The audience ID.
          attr_accessor :type
          attr_accessor :description # The audience's name.
          attr_accessor :created # When the audience was created (in UNIX time).
          attr_accessor :request_id # The request ID that was specified when the audience was created.

          def initialize(
            audience_group_id: nil,
            type: nil,
            description: nil,
            created: nil,
            request_id: nil
          )
            
            @audience_group_id = audience_group_id
            @type = type
            @description = description
            @created = created
            @request_id = request_id
          end
        end
      end
    end
  end
end
