# LINE Messaging API
# This document describes LINE Messaging API.
#
# The version of the OpenAPI document: 0.0.1
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

# Owner of this audience group.
module Line
  module Bot
    module V2
      module ManageAudience
        class DetailedOwner
          attr_accessor :service_type # Service name where the audience group has been created.
          attr_accessor :id # Owner ID in the service.
          attr_accessor :name # Owner account name.

          def initialize(
            service_type: nil,
            id: nil,
            name: nil
          )
            
            @service_type = service_type
            @id = id
            @name = name
          end
        end
      end
    end
  end
end
