# This file is autogenerated.
#
# Generated by scripts/unified-client-generator/main.rb
# Do not edit this file directly.

module Line
  module Bot
    module V2
      class Client
        private

        def build_generated_delegates(
          channel_access_token:,
          api_base_url: nil,
          data_api_base_url: nil,
          http_options: {}
        )
          @insight = Line::Bot::V2::Insight::ApiClient.
            new(base_url: api_base_url, channel_access_token: channel_access_token, http_options: http_options)

          @liff = Line::Bot::V2::Liff::ApiClient.
            new(base_url: api_base_url, channel_access_token: channel_access_token, http_options: http_options)

          @manage_audience = Line::Bot::V2::ManageAudience::ApiClient.
            new(base_url: api_base_url, channel_access_token: channel_access_token, http_options: http_options)

          @manage_audience_blob = Line::Bot::V2::ManageAudience::ApiBlobClient.
            new(base_url: data_api_base_url, channel_access_token: channel_access_token, http_options: http_options)

          @messaging_api = Line::Bot::V2::MessagingApi::ApiClient.
            new(base_url: api_base_url, channel_access_token: channel_access_token, http_options: http_options)

          @messaging_api_blob = Line::Bot::V2::MessagingApi::ApiBlobClient.
            new(base_url: data_api_base_url, channel_access_token: channel_access_token, http_options: http_options)

          @line_module = Line::Bot::V2::Module::ApiClient.
            new(base_url: api_base_url, channel_access_token: channel_access_token, http_options: http_options)

          @shop = Line::Bot::V2::Shop::ApiClient.
            new(base_url: api_base_url, channel_access_token: channel_access_token, http_options: http_options)
          nil
        end
      end
    end
  end
end
