=begin
#Webhook Type Definition

#Webhook event definition of the LINE Messaging API

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.0.0

=end

# Common files
require 'line_client_webhook/api_client'
require 'line_client_webhook/api_error'
require 'line_client_webhook/version'
require 'line_client_webhook/configuration'

# Models
require 'line_client_webhook/models/action_result'
require 'line_client_webhook/models/beacon_content'
require 'line_client_webhook/models/callback_request'
require 'line_client_webhook/models/chat_control'
require 'line_client_webhook/models/content_provider'
require 'line_client_webhook/models/delivery_context'
require 'line_client_webhook/models/emoji'
require 'line_client_webhook/models/event'
require 'line_client_webhook/models/event_mode'
require 'line_client_webhook/models/image_set'
require 'line_client_webhook/models/joined_members'
require 'line_client_webhook/models/left_members'
require 'line_client_webhook/models/link_content'
require 'line_client_webhook/models/mention'
require 'line_client_webhook/models/mentionee'
require 'line_client_webhook/models/message_content'
require 'line_client_webhook/models/module_content'
require 'line_client_webhook/models/postback_content'
require 'line_client_webhook/models/scenario_result'
require 'line_client_webhook/models/source'
require 'line_client_webhook/models/things_content'
require 'line_client_webhook/models/unsend_detail'
require 'line_client_webhook/models/video_play_complete'
require 'line_client_webhook/models/account_link_event'
require 'line_client_webhook/models/activated_event'
require 'line_client_webhook/models/all_mentionee'
require 'line_client_webhook/models/attached_module_content'
require 'line_client_webhook/models/audio_message_content'
require 'line_client_webhook/models/beacon_event'
require 'line_client_webhook/models/bot_resumed_event'
require 'line_client_webhook/models/bot_suspended_event'
require 'line_client_webhook/models/deactivated_event'
require 'line_client_webhook/models/detached_module_content'
require 'line_client_webhook/models/file_message_content'
require 'line_client_webhook/models/follow_event'
require 'line_client_webhook/models/group_source'
require 'line_client_webhook/models/image_message_content'
require 'line_client_webhook/models/join_event'
require 'line_client_webhook/models/leave_event'
require 'line_client_webhook/models/link_things_content'
require 'line_client_webhook/models/location_message_content'
require 'line_client_webhook/models/member_joined_event'
require 'line_client_webhook/models/member_left_event'
require 'line_client_webhook/models/message_event'
require 'line_client_webhook/models/module_event'
require 'line_client_webhook/models/postback_event'
require 'line_client_webhook/models/room_source'
require 'line_client_webhook/models/scenario_result_things_content'
require 'line_client_webhook/models/sticker_message_content'
require 'line_client_webhook/models/text_message_content'
require 'line_client_webhook/models/things_event'
require 'line_client_webhook/models/unfollow_event'
require 'line_client_webhook/models/unlink_things_content'
require 'line_client_webhook/models/unsend_event'
require 'line_client_webhook/models/user_mentionee'
require 'line_client_webhook/models/user_source'
require 'line_client_webhook/models/video_message_content'
require 'line_client_webhook/models/video_play_complete_event'

# APIs
require 'line_client_webhook/api/dummy_api'

module LINE::Client::Webhook
  class << self
    # Customize default settings for the SDK using block.
    #   LINE::Client::Webhook.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
