name: Pull Request CI

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        # https://www.ruby-lang.org/en/downloads/branches/
        ruby:
          - '3.3'
          - '3.4'
          - '4.0'
    name: Ruby v${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: true
    - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        distribution: 'temurin'
        java-version: 17
        architecture: x64
    - run: bundle install
    - run: python3 generate-code.py
    - run: bundle exec rake ci

  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          skip_push: "true"
