name: Pull Request CI

on:
  push:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        # https://www.ruby-lang.org/en/downloads/branches/
        ruby:
          - '3.3'
          - '3.4'
          - '4.0'
    name: Ruby v${{ matrix.ruby }}
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        submodules: true
    - uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: 'temurin'
        java-version: 17
        architecture: x64
    - run: bundle install
    - run: python3 generate-code.py
    - run: bundle exec rake ci

  pinact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@896d595f299e71d65b9d28349d6956abe144390a # v3.0.0
        with:
          skip_push: "true"
